[build]
builder = "dockerfile"
dockerfile = "Dockerfile"

[deploy]
# Użyj niestandardowego skryptu startowego zamiast artisan serve
startCommand = "/var/www/start.sh"
healthcheckPath = "/"
healthcheckTimeout = 300
