[build]
builder = "dockerfile"
dockerfile = "Dockerfile"

[deploy]
# Użyj niestandardowego skryptu startowego zamiast artisan serve
startCommand = "php railway-server.php"
healthcheckPath = "/"
healthcheckTimeout = 300
