version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www
        depends_on:
            - mysql
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_DATABASE=laravel
            - DB_USERNAME=laravel
            - DB_PASSWORD=secret
            - VITE_DEV_SERVER_URL=http://localhost:5173

    mysql:
        image: mysql:8.0
        ports:
            - "3307:3306"
        environment:
            - MYSQL_DATABASE=laravel
            - MYSQL_USER=laravel
            - MYSQL_PASSWORD=secret
            - MYSQL_ROOT_PASSWORD=secret
        volumes:
            - mysql-data:/var/lib/mysql

    node:
        image: node:20
        volumes:
            - .:/app
        working_dir: /app
        command: bash -c "npm install && npm run dev"
        ports:
            - "5173:5173"
        environment:
            - HOST=0.0.0.0

volumes:
    mysql-data:
