# docker-compose.override.yml
version: '3.8'

services:
  # Serwer deweloperski Vite
  vite:
    image: node:20-alpine
    container_name: bank-vite
    volumes:
      - ./:/var/www
    working_dir: /var/www
    entrypoint: ["npm", "run", "dev"]
    environment:
      - HOST=0.0.0.0
    ports:
      - "5173:5173"
    networks:
      - bank-network
    depends_on:
      - app

  app:
    environment:
      - VITE_SERVER_HOST=vite
      - VITE_SERVER_PORT=5173
