version: '3.8'

services:
    # Główna aplikacja PHP
    app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                user: laravel
                uid: 1000
        container_name: bank-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - bank-network
        depends_on:
            - mysql

    # Serwer Web NGINX
    nginx:
        image: nginx:1.25-alpine
        container_name: bank-nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - bank-network
        depends_on:
            - app

    # Baza danych MySQL
    mysql:
        image: mysql:8.0
        container_name: bank-mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - bank-network
        command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0

    # Node.js dla kompilacji zasobów frontendowych
    node:
        image: node:20-alpine
        container_name: bank-node
        volumes:
            - ./:/var/www
        working_dir: /var/www
        entrypoint: ["sh", "-c"]
        command: ["npm install && npm run build"]
        networks:
            - bank-network

    # phpMyAdmin dla zarządzania bazą danych
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: bank-phpmyadmin
        restart: unless-stopped
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-secret}
        ports:
            - "8080:80"
        networks:
            - bank-network
        depends_on:
            - mysql

networks:
    bank-network:
        driver: bridge

volumes:
    mysql-data:
        driver: local
