[build]
builder = "nixpacks"
buildCommand = "composer install --no-dev && npm install && npm run build"

[deploy]
startCommand = "php -S 0.0.0.0:8000 -t public"
healthcheckPath = "/"
healthcheckTimeout = 100
