[build]
builder = "nixpacks"
buildCommand = "composer install && npm install && npm run build"

[deploy]
startCommand = "php artisan config:clear && php artisan cache:clear && php artisan key:generate --force && php artisan migrate:fresh --force --seed && php -S 0.0.0.0:8080 -t public"
restartPolicyType = "on_failure"
