[build]
builder = "nixpacks"
buildCommand = "composer install --optimize-autoloader --no-dev && npm install && npm run build"

[deploy]
startCommand = "php artisan migrate:fresh --force --seed && php -S 0.0.0.0:8000 -t public"
restartPolicyType = "on_failure"
