[build]
builder = "nixpacks"
buildCommand = "composer install && php artisan key:generate --force && npm install && npm run build"

[deploy]
startCommand = "echo 'DB Config:' && php artisan config:get database && php artisan migrate --force --no-interaction --verbose && php -S 0.0.0.0:8000 -t public"
# Usuń healthcheckPath i healthcheckTimeout całkowicie
restartPolicyType = "on_failure"
